server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalogo-service
          uri: lb://catalogo-service
          predicates:
            - Path=/categoria/**,/producto/**
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**

